# Generated by Django 2.1.10 on 2019-10-17 18:23

import academycity.apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(0, 'Other'), (1, 'General Ledger')], default=1)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='adjectivesvalues',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=1),
        ),
    ]
