# Generated by Django 3.0.10 on 2020-12-07 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0055_auto_20201108_0027'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(default='black', max_length=100)),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule_whitheboards', to='courses.CourseSchedule')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardnames', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(default='black', on_delete=django.db.models.deletion.CASCADE, to='courses.Section')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteboardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='black', max_length=10)),
                ('xf', models.SmallIntegerField()),
                ('yf', models.SmallIntegerField()),
                ('xt', models.SmallIntegerField()),
                ('yt', models.SmallIntegerField()),
                ('painter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to='chat.Whiteboard')),
            ],
        ),
    ]
