# Generated by Django 3.0.10 on 2020-12-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_whiteboard_whiteboarddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboarddata',
            name='mode',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='whiteboarddata',
            name='pen_size',
            field=models.SmallIntegerField(default=2),
        ),
    ]
