# Generated by Django 3.0.10 on 2020-12-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201207_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whiteboarddata',
            options={'ordering': ['id'], 'verbose_name': 'whiteboarddata', 'verbose_name_plural': 'whiteboarddatas'},
        ),
    ]
